services:
    api:
        build:
            context: .
            dockerfile: Dockerfile.development
        restart: always
        ports:
            - '8080:8080'
        volumes:
            - './src:/usr/app/src'
        working_dir: /usr/app/src
        links:
            - mongo
    mongo:
        image: mongo:8.0.1
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=Test123
            - MONGO_INITDB_DATABASE=linkme
        ports:
            - '27017:27017'
